### PR TITLE
feat: support connectivity check callback

### PR DESCRIPTION
**Pull request by mzz2017**
### Background

支持将连接检查的结果反馈给前端。

通过 `/ws` 接口，需要传入 authorization 的 param（query）。

格式：
```json
{
    "Type": "ConnectivityCheck_Done",
    "Timestamp": "2023-12-10T09:23:48.364491779Z",
    "Body": {
        "DialerProperty": {
            "Name": "xxxx",
            "Address": "xxxx",
            "Protocol": "vmess",
            "Link": "xxxx",
            "SubscriptionTag": ""
        },
        "CheckType": {
            "L4Proto": "tcp",
            "IpVersion": "4",
            "IsDns": true
        },
        "Latency": 273,
        "Alive": true,
        "Err": null
    }
}
```

Latency 单位为 ms，为 10000 意为 timeout。

IsDns 表示这个测试是否通过 dns 请求来测试的，来测试 dns 的 tcp/udp 联通性。

注意事项：这个接口需要前端发送 keepalive 字样，如果 2 分钟没有任何消息会掐断连接。

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae-wing

### Full Changelogs

- [Implement ...]

### Issue Reference

Fix #_[issue number]_

### CODE REVIEW

**Comment by kecrily** [comment]
Wants to return data to add fields about whether the node was selected and by which groups.

**Comment by kecrily** [comment]
Based on the way dae-wing is used, I think it's inevitable that will cross origin. We should redesign `NewUpgrader.checkSameOrigin` to override [default security policy](https://github.com/lesismal/nbio/blob/5bf91e67b31f0d6587adc3ecbda9956a2d788990/nbhttp/websocket/upgrader.go#L538-L544) or simply skip the check.

**Comment by kecrily** [comment]
Due to the lack of `NewUpgrader.KeepaliveTime`, ping/pong cannot keep alive properly.

**Comment by mzz2017** [comment]
@kecrily Your request is very accurate and has been fixed. Thank you! 🙏

**Pull request merged**
