### PR TITLE
fix: bad affiliations between nodes and groups in config generation

### PR DESCRIPTION
**Pull request by mzz2017**
# Background
Nodes in all groups are incorrectly the same.

# Changes
Clear the affiliations between nodes and groups in config generation.

### CODE REVIEW

**Comment by kunish** [comment]
How do I test this?

**Comment by mzz2017** [comment]
@kunish 
image
Use two groups with different nodes. And to see whether every group has the correct nodes in them (turn on debug level to see the generated configuration).

**Comment by kunish** [comment]
The only group I can find (with debug level turned on) is the one currently referenced by the running routing rule.

**Comment by mzz2017** [comment]
> The only group I can find (with debug level turned on) is the one currently referenced by the running routing rule.

Yes, you can add a routing rule to reference it and try again.

**Review by kunish — APPROVED** [review]
Working as expected

**Pull request merged**
